unique_ids:
  assets:
    standard-page.html: IY2TQUF2KHH67O2VYJ4IBUBWASSJVHY2
    theme.css: UY4XII4CH2UZSIELUVS7XXOEL2A3MO5P
  forms:
    Form1: 2HJQHY5DTZTWJF3GVSTSDOD5GJ3GGJTD
  modules: {}
  scripts: {}
  server_modules: {}
